language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t alexis59495/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true alexis59495/docker-react npm run test